# Generated by Django 3.0.8 on 2024-10-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stopwatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(default=0)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
            ],
        ),
    ]
