# Generated by Django 3.0.8 on 2024-10-07 23:36

# Migration files modifies the database

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stopwatch', #Creates a table named 'Stopwatch'
            fields=[ #Below are the fields and columns of the table
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(default=0)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
            ],
        ),
    ]
