# Generated by Django 5.1.1 on 2024-10-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studyapp", "0004_studystreak"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudyStreak",
        ),
    ]
