# Generated by Django 5.1.1 on 2024-10-28 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyapp", "0005_delete_studystreak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stopwatch",
            name="time_spent",
            field=models.IntegerField(default=django.utils.timezone.now),
        # get time now
        ),
        migrations.AlterField(
            model_name="stopwatch",
            name="time_start",
            field=models.DateTimeField(),
        ),
    ]
