# Generated by Django 5.1.1 on 2024-10-28 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyapp", "0006_alter_stopwatch_time_spent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stopwatch",
            name="time_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stopwatch",
            name="time_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]

# Cd to project directory and run the following line to consolidate migration files and remove redundancies
# python manage.py squashmigrations studyapp <first_migration> <last_migration>