# Generated by Django 5.1.1 on 2024-11-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0007_alter_stopwatch_time_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopwatch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='stopwatch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True),
        ),
    ]
